export const inPatientTableHeadiing = [
    {
        name:"SI.no.",
        path:"si.no."
    },
    {
        name:"Patient Id",
        path1:"patientId",
        path2:"patientId",
        isNested:true
    },
    {
        name:"Patient Name",
        path1:"patientId",
        path2:"patientName",
        path3:"name",
        isDoubleNested:true
    },
    {
        name:"Age",
        path1:"patientId",
        path2:"age",
        isNested:true
    },
    {
        name:"Gender",
        path1:"patientId",
        path2:"gender",
        isNested:true
    },
    {
        name:"Blood Group",
        path1:"patientId",
        path2:"bloodGroup",
        isNested:true
    },
    {
        name:"Phone Number",
        path1:"patientId",
        path2:"mobileNumber",
        path3:"number",
        isDoubleNested:true

    },
    {
        name:"Room No.",
        path1:"patientId",
        path2:"roomNumber"
    },
    {
        name:"Status",
        path:"status",
        type:"blueTag"
    },
    {
        name:"Action",
        path:"normal",
    }
]

export const inPatientTableValue = [
    {
        id:"11",
        patientId:"32325",
        patientName:"Ajay",
        age:"25",
        gender:"Male",
        bloodGroup:"A+",
        phoneNumber:"1234567890",
        roomNumber:"101",
        status:"Pending",
    },
    {
        id:"12",
        patientId:"32325",
        patientName:"Ajay",
        age:"25",
        gender:"Male",
        bloodGroup:"A +ive",
        phoneNumber:"1234567890",
        roomNumber:"101",
        status:"allocated",
    },
    {
        id:"13",
        patientId:"32325",
        patientName:"Ajay",
        age:"25",
        gender:"Male",
        bloodGroup:"A+",
        phoneNumber:"1234567890",
        roomNumber:"101",
        status:"Pending",
    },
    {
        id:"14",
        patientId:"32325",
        patientName:"Ajay",
        age:"25",
        gender:"Male",
        bloodGroup:"A+",
        phoneNumber:"1234567890",
        roomNumber:"101",
        status:"allocated",
    },
    {
        id:"15",
        patientId:"32325",
        patientName:"Ajay",
        age:"25",
        gender:"Male",
        bloodGroup:"A+",
        phoneNumber:"1234567890",
        roomNumber:"101",
        status:"Pending",
    },
]

export const roomAllotmentData = [
    {
        room:"1",
        occupied:true
    },
    {
        room:"2",
        occupied:false
    },
    {
        room:"3",
        occupied:false
    },
    {
        room:"4",
        occupied:false
    },
    {
        room:"5",
        occupied:true
    },
    {
        room:"6",
        occupied:false
    },
    {
        room:"7",
        occupied:false
    },
    {
        room:"8",
        occupied:true
    },
    {
        room:"9",
        occupied:true
    },

]